version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    image: khlestkov/app
    environment:
      MYSQL_URL: jdbc:mysql://db:3311/mydbtest
      SERVER_PORT: 8081
    volumes:
      - ./:/app
    depends_on:
    - db
    networks:
      - mynetwork

  db:
    image: mysql
    container_name: db
    restart: always  #если контейнер упадет, он будет перезапущен
    ports:
      - "3311:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydbtest
    networks:
      - mynetwork
networks:
  mynetwork:




